<a href="https://colab.research.google.com/github/Ajaykumar-02/NLP/blob/main/BagOfWords.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
from sklearn.feature_extraction.text import CountVectorizer

In [10]:
from numpy import vectorize
documnets = [
    "I love pizza",
    "Pizza is the best",
    "I love pasta",
    "Pasta is great"
]

vectorizer = CountVectorizer(ngram_range=(1,3))

X = vectorizer.fit_transform(documnets)

print("Vocabulary:", vectorizer.get_feature_names_out())
print("\nBow Matrix:\n",X.toarray())

Vocabulary: ['best' 'great' 'is' 'is great' 'is the' 'is the best' 'love' 'love pasta'
 'love pizza' 'pasta' 'pasta is' 'pasta is great' 'pizza' 'pizza is'
 'pizza is the' 'the' 'the best']

Bow Matrix:
 [[0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0]
 [1 0 1 0 1 1 0 0 0 0 0 0 1 1 1 1 1]
 [0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0]
 [0 1 1 1 0 0 0 0 0 1 1 1 0 0 0 0 0]]
